-- Pharmacon Supabase schema

create extension if not exists pgcrypto;

-- --------------------------------------------------------------------------
-- Profiles / authentication metadata
-- Supabase Auth owns credentials in auth.users. This table stores app roles.
-- Demo accounts can be created by deploying/invoking supabase/functions/bootstrap-demo-users.
-- --------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  name text not null,
  role text not null check (role in ('doctor','clinic-staff','pharmacist','patient','admin','instructor')),
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_role() in ('admin','instructor'), false);
$$;

alter table public.profiles enable row level security;

drop policy if exists "Profiles can be read by the owner" on public.profiles;
create policy "Profiles can be read by the owner"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles"
  on public.profiles for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- --------------------------------------------------------------------------
-- Core project tables
-- --------------------------------------------------------------------------
create table if not exists public.versions (
  id text primary key,
  name text not null,
  date text not null,
  authors text not null,
  status text not null check (status in ('current','archived','future','draft')),
  change_summary text not null default '',
  commit_ref text default '',
  deployment_url text default '',
  parent_version_id text references public.versions(id) on delete set null,
  file_url text default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.deliverables (
  id text primary key,
  title text not null,
  type text not null,
  version_id text references public.versions(id) on delete set null,
  version_name text default '',
  date text not null,
  status text not null check (status in ('draft','in-progress','published','archived')),
  description text not null default '',
  file_id text,
  file_name text,
  file_url text,
  authors text default 'Team Pharmacon',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.team_members (
  id text primary key,
  name text not null,
  role text not null,
  focus text not null,
  avatar text not null,
  skills text not null default '',
  avatar_file_id text,
  github_url text default '',
  linkedin_url text default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory_items (
  id text primary key,
  medicine text not null,
  strength text not null,
  dosage_form text not null,
  sku text unique not null,
  pack_size text not null,
  stock integer not null default 0,
  reorder_level integer not null default 10,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.prescriptions (
  id text primary key,
  patient_id text not null,
  patient_name text not null,
  doctor_name text not null,
  status text not null check (status in ('draft','confirmed','dispensed')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.prescription_fields (
  id bigint generated by default as identity primary key,
  prescription_id text not null references public.prescriptions(id) on delete cascade,
  label text not null,
  value text not null,
  confidence integer not null,
  needs_verification integer not null default 0
);

create table if not exists public.refill_requests (
  id text primary key,
  prescription_id text references public.prescriptions(id),
  patient_id text not null,
  patient_name text not null,
  medicine text not null,
  strength text not null,
  status text not null check (status in ('pending','approved','rejected','contacted')),
  requested_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_events (
  id text primary key,
  actor text not null,
  role text not null,
  action text not null,
  entity text not null,
  entity_id text not null,
  status text not null check (status in ('success','warning','info')),
  details text default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.page_content (
  id text primary key,
  page text not null,
  section text not null,
  items jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  unique(page, section)
);

create table if not exists public.presentation_decks (
  id text primary key,
  title text not null,
  description text not null default '',
  file_path text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.files (
  id text primary key,
  filename text not null,
  original_name text not null,
  mime_type text not null,
  size bigint not null,
  storage_path text not null unique,
  file_url text not null,
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now())
);

-- Existing installations: add columns missing from the older schema.
alter table public.deliverables add column if not exists file_id text;
alter table public.deliverables add column if not exists file_name text;
alter table public.deliverables add column if not exists file_url text;
alter table public.team_members add column if not exists avatar_file_id text;
alter table public.versions add column if not exists file_url text default '';

-- --------------------------------------------------------------------------
-- Constraints that can be created after both sides exist.
-- --------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'deliverables_file_id_fkey') then
    alter table public.deliverables
      add constraint deliverables_file_id_fkey foreign key (file_id) references public.files(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'team_members_avatar_file_id_fkey') then
    alter table public.team_members
      add constraint team_members_avatar_file_id_fkey foreign key (avatar_file_id) references public.files(id) on delete set null;
  end if;
end $$;

-- --------------------------------------------------------------------------
-- RLS
-- --------------------------------------------------------------------------
alter table public.versions enable row level security;
alter table public.deliverables enable row level security;
alter table public.team_members enable row level security;
alter table public.inventory_items enable row level security;
alter table public.prescriptions enable row level security;
alter table public.prescription_fields enable row level security;
alter table public.refill_requests enable row level security;
alter table public.audit_events enable row level security;
alter table public.page_content enable row level security;
alter table public.presentation_decks enable row level security;
alter table public.files enable row level security;

-- Versions
 drop policy if exists "Public read versions" on public.versions;
create policy "Public read versions" on public.versions for select using (true);
 drop policy if exists "Admins manage versions" on public.versions;
create policy "Admins manage versions" on public.versions for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Deliverables
 drop policy if exists "Public read deliverables" on public.deliverables;
create policy "Public read deliverables" on public.deliverables for select using (true);
 drop policy if exists "Admins manage deliverables" on public.deliverables;
create policy "Admins manage deliverables" on public.deliverables for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Team
 drop policy if exists "Public read team" on public.team_members;
create policy "Public read team" on public.team_members for select using (true);
 drop policy if exists "Admins manage team" on public.team_members;
create policy "Admins manage team" on public.team_members for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Inventory is visible to the app but writable only by admins.
 drop policy if exists "Authenticated read inventory" on public.inventory_items;
create policy "Authenticated read inventory" on public.inventory_items for select to authenticated using (true);
 drop policy if exists "Admins manage inventory" on public.inventory_items;
create policy "Admins manage inventory" on public.inventory_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Prescriptions are authenticated-only; changes are performed through role-aware flows/RPCs.
 drop policy if exists "Authenticated read prescriptions" on public.prescriptions;
create policy "Authenticated read prescriptions" on public.prescriptions for select to authenticated using (true);
 drop policy if exists "Admins manage prescriptions" on public.prescriptions;
create policy "Admins manage prescriptions" on public.prescriptions for all to authenticated using (public.is_admin()) with check (public.is_admin());

 drop policy if exists "Authenticated read prescription fields" on public.prescription_fields;
create policy "Authenticated read prescription fields" on public.prescription_fields for select to authenticated using (true);
 drop policy if exists "Admins manage prescription fields" on public.prescription_fields;
create policy "Admins manage prescription fields" on public.prescription_fields for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Refills: authenticated users can see requests; patients can create their own, admins/staff can update.
 drop policy if exists "Authenticated read refills" on public.refill_requests;
create policy "Authenticated read refills" on public.refill_requests for select to authenticated using (true);
 drop policy if exists "Patients create own refills" on public.refill_requests;
create policy "Patients create own refills" on public.refill_requests for insert to authenticated
  with check (patient_id = auth.uid()::text or public.is_admin() or public.current_role() in ('doctor','clinic-staff','pharmacist'));
 drop policy if exists "Staff update refills" on public.refill_requests;
create policy "Staff update refills" on public.refill_requests for update to authenticated
  using (public.current_role() in ('admin','instructor','pharmacist','clinic-staff'))
  with check (public.current_role() in ('admin','instructor','pharmacist','clinic-staff'));

-- Audit is authenticated-only and append-only outside admin/RPC contexts.
 drop policy if exists "Authenticated read audit" on public.audit_events;
create policy "Authenticated read audit" on public.audit_events for select to authenticated using (true);
 drop policy if exists "Authenticated append audit" on public.audit_events;
create policy "Authenticated append audit" on public.audit_events for insert to authenticated with check (true);
 drop policy if exists "Admins manage audit" on public.audit_events;
create policy "Admins manage audit" on public.audit_events for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Editable page content / decks: public read, admin write.
 drop policy if exists "Public read page content" on public.page_content;
create policy "Public read page content" on public.page_content for select using (true);
 drop policy if exists "Admins manage page content" on public.page_content;
create policy "Admins manage page content" on public.page_content for all to authenticated using (public.is_admin()) with check (public.is_admin());

 drop policy if exists "Public read presentation decks" on public.presentation_decks;
create policy "Public read presentation decks" on public.presentation_decks for select using (true);
 drop policy if exists "Admins manage presentation decks" on public.presentation_decks;
create policy "Admins manage presentation decks" on public.presentation_decks for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Files are only visible to authenticated users; storage objects are public for the
-- deliverable bucket so public deliverable pages can link directly to artifacts.
 drop policy if exists "Authenticated read files" on public.files;
create policy "Authenticated read files" on public.files for select to authenticated using (true);
 drop policy if exists "Users create own files" on public.files;
create policy "Admins create files" on public.files for insert to authenticated with check (uploaded_by = auth.uid() and public.is_admin());
 drop policy if exists "Admins delete files" on public.files;
create policy "Admins delete files" on public.files for delete to authenticated using (public.is_admin());

-- --------------------------------------------------------------------------
-- Storage
-- --------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('deliverables', 'deliverables', true, 104857600)
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit;

 drop policy if exists "Public read deliverable objects" on storage.objects;
create policy "Public read deliverable objects"
  on storage.objects for select
  using (bucket_id = 'deliverables');

 drop policy if exists "Authenticated upload deliverable objects" on storage.objects;
create policy "Authenticated upload deliverable objects"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'deliverables' and (storage.foldername(name))[1] = auth.uid()::text and public.is_admin());

 drop policy if exists "Admins delete deliverable objects" on storage.objects;
create policy "Admins delete deliverable objects"
  on storage.objects for delete to authenticated
  using (bucket_id = 'deliverables' and public.is_admin());

-- --------------------------------------------------------------------------
-- Transactional functions
-- --------------------------------------------------------------------------
create or replace function public.set_current_version(target_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'insufficient permissions';
  end if;
  update public.versions set status = 'archived' where status = 'current' and id <> target_id;
  update public.versions set status = 'current' where id = target_id;
end;
$$;

create or replace function public.confirm_sample_prescription()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_id text;
  actor_name text;
  actor_role text;
begin
  if public.current_role() not in ('admin','instructor','doctor','clinic-staff') then
    raise exception 'insufficient permissions';
  end if;

  select id into existing_id from public.prescriptions where id = 'RX-DEMO-CONFIRMED';
  if existing_id is not null then
    return jsonb_build_object('prescriptionId', existing_id, 'alreadyConfirmed', true);
  end if;

  select name, role into actor_name, actor_role from public.profiles where id = auth.uid();

  insert into public.prescriptions (id, patient_id, patient_name, doctor_name, status)
  values ('RX-DEMO-CONFIRMED', 'PT-1001', 'Rahul Kumar', 'Dr. A. Sharma', 'confirmed');

  insert into public.prescription_fields (prescription_id, label, value, confidence, needs_verification) values
    ('RX-DEMO-CONFIRMED','Medicine','Amoxicillin',94,0),
    ('RX-DEMO-CONFIRMED','Strength','500 mg',97,0),
    ('RX-DEMO-CONFIRMED','Dosage Form','Tablet',96,0),
    ('RX-DEMO-CONFIRMED','Frequency','1-0-1',86,1),
    ('RX-DEMO-CONFIRMED','Route','Oral',92,0),
    ('RX-DEMO-CONFIRMED','Duration','5 days',91,0),
    ('RX-DEMO-CONFIRMED','Instructions','After food',88,1);

  update public.inventory_items
  set stock = greatest(stock - 1, 0), updated_at = timezone('utc', now())
  where id = 'INV-001';

  insert into public.audit_events (id, actor, role, action, entity, entity_id, status, details)
  values
    ('AE-' || substr(gen_random_uuid()::text, 1, 8), coalesce(actor_name, 'Staff User'), coalesce(actor_role, 'clinic-staff'), 'Prescription confirmed', 'Prescription', 'RX-DEMO-CONFIRMED', 'success', ''),
    ('AE-' || substr(gen_random_uuid()::text, 1, 8), 'System', 'System', 'Inventory adjusted', 'Inventory', 'INV-001', 'success', '');

  return jsonb_build_object('prescriptionId', 'RX-DEMO-CONFIRMED', 'alreadyConfirmed', false);
end;
$$;

grant execute on function public.set_current_version(text) to authenticated;
grant execute on function public.confirm_sample_prescription() to authenticated;

-- --------------------------------------------------------------------------
-- Seed data
-- --------------------------------------------------------------------------
insert into public.team_members (id, name, role, focus, avatar, skills, github_url, linkedin_url) values
('T-001', 'Aryan Sharma', 'Frontend Lead', 'UI/UX architecture, responsive design system, tactile component library, and interactive presentations.', 'AS', 'React, Vite, TypeScript, Tailwind CSS, Recharts', 'https://github.com', 'https://linkedin.com'),
('T-002', 'Aniket Raj', 'Backend Lead', 'Supabase architecture, PostgreSQL persistence, storage integrations, and release publishing engine.', 'AR', 'TypeScript, PostgreSQL, Supabase, REST APIs', 'https://github.com', 'https://linkedin.com'),
('T-003', 'Amitesh Kumar Singh', 'AI / CV Engineer', 'Handwriting segmentation pipeline, CNN-Transformer feature models, and doctor-adaptive calibration loops.', 'AK', 'Python, PyTorch, Computer Vision, OCR, CNN-Transformers', 'https://github.com', 'https://linkedin.com'),
('T-004', 'Chirag Lamba', 'Integration Lead', 'Formulary SKU matching algorithms, security audit controls, end-to-end reliability verification, and CI/CD pipelines.', 'CL', 'CI/CD, GitHub Actions, System Integration, Testing, Security Audit', 'https://github.com', 'https://linkedin.com')
on conflict (id) do update set name=excluded.name, role=excluded.role, focus=excluded.focus, skills=excluded.skills, github_url=excluded.github_url, linkedin_url=excluded.linkedin_url;

insert into public.versions (id, name, date, authors, status, change_summary, commit_ref, deployment_url, file_url) values
('v1.0.0', 'Planning Presentation v1', '2026-08-25', 'Aryan Sharma, Aniket Raj, Amitesh Kumar Singh, Chirag Lamba', 'current', 'Initial project planning deliverable covering scope, intended users, system architecture, performance goals, technical risks, and interactive Gantt roadmap.', 'main@a89c42e', '#/presentation/v1', '/presentations/Pharmacon_Commitment_Pitch.pptx'),
('v2.0.0', 'Planning Presentation v2', '2026-09-10', 'Team Pharmacon', 'future', 'Refined scope addressing writer recruitment milestones, real clinic calibration workflows, and Supabase integration.', 'dev@f190b21', '#/presentation/v2', '')
on conflict (id) do update set name=excluded.name, date=excluded.date, authors=excluded.authors, status=excluded.status, change_summary=excluded.change_summary, commit_ref=excluded.commit_ref, deployment_url=excluded.deployment_url, file_url=excluded.file_url;

insert into public.deliverables (id, title, type, version_id, version_name, date, status, description, file_name, file_url, authors) values
('deliv-v1-deck', 'Planning Presentation v1 (Interactive Web Deck)', 'Interactive Presentation', 'v1.0.0', 'Planning Presentation v1', '2026-08-25', 'published', 'Direct browser-delivered planning presentation satisfying all UCS503 requirements.', 'Pharmacon_Commitment_Pitch.pptx', '/presentations/Pharmacon_Commitment_Pitch.pptx', 'Team Pharmacon (Aryan, Aniket, Amitesh, Chirag)'),
('deliv-v2-deck', 'Planning Presentation v2 (Scope & Feedback Updates)', 'Interactive Presentation', 'v2.0.0', 'Planning Presentation v2', '2026-09-10', 'published', 'Updated planning deliverable incorporating instructor feedback and revised architecture.', 'Planning_V2_Updated.pptx', '', 'Team Pharmacon')
on conflict (id) do update set title=excluded.title, type=excluded.type, version_id=excluded.version_id, version_name=excluded.version_name, date=excluded.date, status=excluded.status, description=excluded.description, file_name=excluded.file_name, file_url=excluded.file_url, authors=excluded.authors;

insert into public.inventory_items (id, medicine, strength, dosage_form, sku, pack_size, stock, reorder_level) values
('INV-001', 'Amoxicillin', '500 mg', 'Capsule', 'AMX-500-CAP', '100 caps', 142, 25),
('INV-002', 'Metformin', '500 mg', 'Tablet', 'MET-500-TAB', '60 tabs', 18, 20),
('INV-003', 'Paracetamol', '650 mg', 'Tablet', 'PAR-650-TAB', '100 tabs', 240, 30),
('INV-004', 'Azithromycin', '500 mg', 'Tablet', 'AZI-500-TAB', '30 tabs', 8, 15)
on conflict (id) do update set medicine=excluded.medicine, strength=excluded.strength, dosage_form=excluded.dosage_form, pack_size=excluded.pack_size, stock=excluded.stock, reorder_level=excluded.reorder_level;

insert into public.prescriptions (id, patient_id, patient_name, doctor_name, status) values
('RX-2024-0001', 'PT-1001', 'Rahul Kumar', 'Dr. A. Sharma', 'confirmed')
on conflict (id) do nothing;

insert into public.prescription_fields (prescription_id, label, value, confidence, needs_verification)
select 'RX-2024-0001', x.label, x.value, x.confidence, x.needs_verification
from (values
  ('Medicine','Amoxicillin',94,0), ('Strength','500 mg',97,0), ('Dosage Form','Tablet',96,0),
  ('Frequency','1-0-1',86,1), ('Route','Oral',92,0), ('Duration','5 days',91,0), ('Instructions','After food',88,1)
) as x(label,value,confidence,needs_verification)
where not exists (select 1 from public.prescription_fields where prescription_id='RX-2024-0001');

insert into public.refill_requests (id, prescription_id, patient_id, patient_name, medicine, strength, status)
values ('RF-001', 'RX-2024-0001', 'PT-1001', 'Rahul Kumar', 'Amoxicillin', '500 mg', 'pending')
on conflict (id) do nothing;

insert into public.audit_events (id, actor, role, action, entity, entity_id, status, details)
values ('AE-001', 'System', 'System', 'Seeded persistent demo workflow', 'Prescription', 'RX-2024-0001', 'info', 'Initial demo data')
on conflict (id) do nothing;

insert into public.presentation_decks (id, title, description, file_path, sort_order) values
('DECK-001', 'Pharmacon Commitment Pitch', 'Revised scope, doctor-adaptive recognition strategy, roadmap and approval requirements.', '/presentations/Pharmacon_Commitment_Pitch.pptx', 0),
('DECK-002', 'Merged Project Ideas Presentation', 'Original team project-ideas deck, including the medication-scheduling concept that preceded Pharmacon''s revised scope.', '/presentations/Merged_Presentation_from_Claude.pptx', 1)
on conflict (id) do update set title=excluded.title, description=excluded.description, file_path=excluded.file_path, sort_order=excluded.sort_order;
